""" Nom: REN
    prénom: Yi
    marticule: 000468901
    Date: 06/02/2019
"""

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1080, 688)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.plateau_label = QtWidgets.QLabel(self.frame)
        self.plateau_label.setGeometry(QtCore.QRect(10, 10, 400, 400))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plateau_label.sizePolicy().hasHeightForWidth())
        self.plateau_label.setSizePolicy(sizePolicy)
        self.plateau_label.setText("")
        self.plateau_label.setObjectName("plateau_label")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(220, 410, 291, 201))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(10, 10, 150, 16))
        self.label_15.setObjectName("label_15")
        self.row_WspinBox = QtWidgets.QSpinBox(self.frame_3)
        self.row_WspinBox.setGeometry(QtCore.QRect(190, 10, 41, 22))
        self.row_WspinBox.setMaximum(7)
        self.row_WspinBox.setObjectName("row_WspinBox")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 150, 16))
        self.label_16.setObjectName("label_16")
        self.col_WspinBox = QtWidgets.QSpinBox(self.frame_3)
        self.col_WspinBox.setGeometry(QtCore.QRect(190, 60, 41, 22))
        self.col_WspinBox.setMaximum(7)
        self.col_WspinBox.setObjectName("col_WspinBox")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(10, 110, 150, 21))
        self.label_20.setObjectName("label_20")
        self.type_wallcomboBox = QtWidgets.QComboBox(self.frame_3)
        self.type_wallcomboBox.setGeometry(QtCore.QRect(170, 110, 100, 22))
        self.type_wallcomboBox.setObjectName("type_wallcomboBox")
        self.type_wallcomboBox.addItem("")
        self.type_wallcomboBox.addItem("")
        self.murpushButton = QtWidgets.QPushButton(self.frame_3)
        self.murpushButton.setGeometry(QtCore.QRect(10, 140, 261, 31))
        self.murpushButton.setObjectName("murpushButton")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(420, 10, 91, 121))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 31, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(10, 90, 31, 16))
        self.label_19.setObjectName("label_19")
        self.murs_noir_label = QtWidgets.QLabel(self.frame_4)
        self.murs_noir_label.setGeometry(QtCore.QRect(60, 50, 21, 16))
        self.murs_noir_label.setObjectName("murs_noir_label")
        self.murs_blanc_label = QtWidgets.QLabel(self.frame_4)
        self.murs_blanc_label.setGeometry(QtCore.QRect(60, 90, 21, 16))
        self.murs_blanc_label.setObjectName("murs_blanc_label")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(20, 430, 191, 101))
        self.frame_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.upButton = QtWidgets.QPushButton(self.frame_5)
        self.upButton.setGeometry(QtCore.QRect(60, 10, 61, 23))
        self.upButton.setAutoRepeatDelay(300)
        self.upButton.setAutoDefault(False)
        self.upButton.setFlat(False)
        self.upButton.setObjectName("upButton")
        self.leftButton = QtWidgets.QPushButton(self.frame_5)
        self.leftButton.setGeometry(QtCore.QRect(10, 40, 61, 23))
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QPushButton(self.frame_5)
        self.rightButton.setGeometry(QtCore.QRect(110, 40, 61, 23))
        self.rightButton.setObjectName("rightButton")
        self.downButton = QtWidgets.QPushButton(self.frame_5)
        self.downButton.setGeometry(QtCore.QRect(60, 70, 51, 23))
        self.downButton.setObjectName("downButton")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(20, 560, 181, 31))
        self.frame_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_14 = QtWidgets.QLabel(self.frame_6)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label_14.setObjectName("label_14")
        self.joueurSuivlabel = QtWidgets.QLabel(self.frame_6)
        self.joueurSuivlabel.setGeometry(QtCore.QRect(110, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.joueurSuivlabel.setFont(font)
        self.joueurSuivlabel.setLineWidth(2)
        self.joueurSuivlabel.setObjectName("joueurSuivlabel")
        self.affichage_label_21 = QtWidgets.QLabel(self.frame)
        self.affichage_label_21.setGeometry(QtCore.QRect(30, 200, 381, 16))
        self.affichage_label_21.setObjectName("affichage_label_21")
        self.gridLayout_2.addWidget(self.frame, 0, 1, 2, 1)
        self.msg_Label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg_Label.sizePolicy().hasHeightForWidth())
        self.msg_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.msg_Label.setFont(font)
        self.msg_Label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.msg_Label.setLineWidth(3)
        self.msg_Label.setObjectName("msg_Label")
        self.gridLayout_2.addWidget(self.msg_Label, 2, 1, 1, 2)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(4)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(17, 285, 210, 16))
        self.label_7.setObjectName("label_7")
        self.learning_rate_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.learning_rate_doubleSpinBox.setGeometry(QtCore.QRect(239, 249, 141, 20))
        self.learning_rate_doubleSpinBox.setMinimum(0.1)
        self.learning_rate_doubleSpinBox.setMaximum(0.9)
        self.learning_rate_doubleSpinBox.setSingleStep(0.01)
        self.learning_rate_doubleSpinBox.setProperty("value", 0.4)
        self.learning_rate_doubleSpinBox.setObjectName("learning_rate_doubleSpinBox")
        self.comparepushButton = QtWidgets.QPushButton(self.frame_2)
        self.comparepushButton.setGeometry(QtCore.QRect(350, 500, 151, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comparepushButton.sizePolicy().hasHeightForWidth())
        self.comparepushButton.setSizePolicy(sizePolicy)
        self.comparepushButton.setObjectName("comparepushButton")
        self.eps_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.eps_doubleSpinBox.setGeometry(QtCore.QRect(239, 213, 141, 20))
        self.eps_doubleSpinBox.setDecimals(2)
        self.eps_doubleSpinBox.setMinimum(0.1)
        self.eps_doubleSpinBox.setMaximum(0.9)
        self.eps_doubleSpinBox.setSingleStep(0.01)
        self.eps_doubleSpinBox.setProperty("value", 0.3)
        self.eps_doubleSpinBox.setObjectName("eps_doubleSpinBox")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(17, 27, 210, 16))
        self.label.setObjectName("label")
        self.loadFileButton = QtWidgets.QPushButton(self.frame_2)
        self.loadFileButton.setGeometry(QtCore.QRect(406, 66, 101, 23))
        self.loadFileButton.setObjectName("loadFileButton")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(17, 180, 210, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.taille_plateau_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.taille_plateau_spinBox.setGeometry(QtCore.QRect(239, 105, 141, 20))
        self.taille_plateau_spinBox.setMinimum(5)
        self.taille_plateau_spinBox.setMaximum(9)
        self.taille_plateau_spinBox.setProperty("value", 5)
        self.taille_plateau_spinBox.setObjectName("taille_plateau_spinBox")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(17, 321, 210, 16))
        self.label_8.setObjectName("label_8")
        self.nbr_entrainm_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.nbr_entrainm_spinBox.setGeometry(QtCore.QRect(239, 321, 141, 20))
        self.nbr_entrainm_spinBox.setMinimum(1000)
        self.nbr_entrainm_spinBox.setMaximum(100000)
        self.nbr_entrainm_spinBox.setSingleStep(1000)
        self.nbr_entrainm_spinBox.setObjectName("nbr_entrainm_spinBox")
        self.nbr_mur_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.nbr_mur_spinBox.setGeometry(QtCore.QRect(239, 141, 141, 20))
        self.nbr_mur_spinBox.setWrapping(False)
        self.nbr_mur_spinBox.setFrame(True)
        self.nbr_mur_spinBox.setMinimum(1)
        self.nbr_mur_spinBox.setMaximum(10)
        self.nbr_mur_spinBox.setObjectName("nbr_mur_spinBox")
        self.saveFileButton = QtWidgets.QPushButton(self.frame_2)
        self.saveFileButton.setGeometry(QtCore.QRect(406, 27, 101, 23))
        self.saveFileButton.setObjectName("saveFileButton")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(17, 141, 210, 16))
        self.label_4.setObjectName("label_4")
        self.newIAButton = QtWidgets.QPushButton(self.frame_2)
        self.newIAButton.setGeometry(QtCore.QRect(17, 501, 151, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newIAButton.sizePolicy().hasHeightForWidth())
        self.newIAButton.setSizePolicy(sizePolicy)
        self.newIAButton.setObjectName("newIAButton")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(17, 66, 210, 16))
        self.label_2.setObjectName("label_2")
        self.fichier_sav_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.fichier_sav_lineEdit.setGeometry(QtCore.QRect(231, 28, 151, 20))
        self.fichier_sav_lineEdit.setObjectName("fichier_sav_lineEdit")
        self.fichier_charg_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.fichier_charg_lineEdit.setGeometry(QtCore.QRect(231, 67, 151, 20))
        self.fichier_charg_lineEdit.setFrame(True)
        self.fichier_charg_lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.fichier_charg_lineEdit.setObjectName("fichier_charg_lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(17, 105, 210, 16))
        self.label_3.setObjectName("label_3")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(17, 429, 210, 16))
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(17, 357, 210, 16))
        self.label_9.setObjectName("label_9")
        self.player2_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.player2_comboBox.setGeometry(QtCore.QRect(239, 465, 141, 20))
        self.player2_comboBox.setObjectName("player2_comboBox")
        self.player2_comboBox.addItem("")
        self.player2_comboBox.addItem("")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(17, 249, 210, 16))
        self.label_6.setObjectName("label_6")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(17, 465, 210, 16))
        self.label_12.setObjectName("label_12")
        self.ia_humainButton = QtWidgets.QPushButton(self.frame_2)
        self.ia_humainButton.setGeometry(QtCore.QRect(20, 540, 147, 23))
        self.ia_humainButton.setObjectName("ia_humainButton")
        self.nbr_comp_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.nbr_comp_spinBox.setGeometry(QtCore.QRect(239, 357, 141, 20))
        self.nbr_comp_spinBox.setMinimum(1000)
        self.nbr_comp_spinBox.setMaximum(10000)
        self.nbr_comp_spinBox.setSingleStep(10)
        self.nbr_comp_spinBox.setProperty("value", 1000)
        self.nbr_comp_spinBox.setObjectName("nbr_comp_spinBox")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(17, 213, 210, 16))
        self.label_5.setObjectName("label_5")
        self.lambda_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.lambda_doubleSpinBox.setGeometry(QtCore.QRect(239, 285, 141, 20))
        self.lambda_doubleSpinBox.setMinimum(0.1)
        self.lambda_doubleSpinBox.setMaximum(0.9)
        self.lambda_doubleSpinBox.setSingleStep(0.01)
        self.lambda_doubleSpinBox.setProperty("value", 0.9)
        self.lambda_doubleSpinBox.setObjectName("lambda_doubleSpinBox")
        self.neurone_inter_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.neurone_inter_spinBox.setGeometry(QtCore.QRect(239, 177, 141, 20))
        self.neurone_inter_spinBox.setMinimum(1)
        self.neurone_inter_spinBox.setProperty("value", 40)
        self.neurone_inter_spinBox.setObjectName("neurone_inter_spinBox")
        self.strategy_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.strategy_comboBox.setGeometry(QtCore.QRect(239, 393, 141, 20))
        self.strategy_comboBox.setObjectName("strategy_comboBox")
        self.strategy_comboBox.addItem("")
        self.strategy_comboBox.addItem("")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(17, 393, 210, 16))
        self.label_10.setObjectName("label_10")
        self.direction_label = QtWidgets.QLabel(self.frame_2)
        self.direction_label.setGeometry(QtCore.QRect(416, 105, 47, 16))
        self.direction_label.setObjectName("direction_label")
        self.humainButton = QtWidgets.QPushButton(self.frame_2)
        self.humainButton.setGeometry(QtCore.QRect(180, 540, 161, 23))
        self.humainButton.setObjectName("humainButton")
        self.player1_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.player1_comboBox.setGeometry(QtCore.QRect(239, 429, 141, 20))
        self.player1_comboBox.setObjectName("player1_comboBox")
        self.player1_comboBox.addItem("")
        self.player1_comboBox.addItem("")
        self.trainIAButton = QtWidgets.QPushButton(self.frame_2)
        self.trainIAButton.setGeometry(QtCore.QRect(180, 500, 161, 23))
        self.trainIAButton.setObjectName("trainIAButton")
        self.train_comp_progressBar = QtWidgets.QProgressBar(self.frame_2)
        self.train_comp_progressBar.setGeometry(QtCore.QRect(20, 570, 481, 23))
        self.train_comp_progressBar.setProperty("value", 0)
        self.train_comp_progressBar.setObjectName("train_comp_progressBar")
        self.gridLayout_2.addWidget(self.frame_2, 0, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "jeu quoridor"))
        self.label_15.setText(_translate("MainWindow", "ligne du mur à placer:"))
        self.label_16.setText(_translate("MainWindow", "colonne du mur à placer:"))
        self.label_20.setText(_translate("MainWindow", "type du mur à placer:"))
        self.type_wallcomboBox.setItemText(0, _translate("MainWindow", "horizontale"))
        self.type_wallcomboBox.setItemText(1, _translate("MainWindow", "verticale"))
        self.murpushButton.setText(_translate("MainWindow", "placer le mur"))
        self.label_17.setText(_translate("MainWindow", "Murs restants :"))
        self.label_18.setText(_translate("MainWindow", "Noir :"))
        self.label_19.setText(_translate("MainWindow", "Blanc :"))
        self.murs_noir_label.setText(_translate("MainWindow", "1"))
        self.murs_blanc_label.setText(_translate("MainWindow", "1"))
        self.upButton.setText(_translate("MainWindow", "up"))
        self.leftButton.setText(_translate("MainWindow", "left"))
        self.rightButton.setText(_translate("MainWindow", "right"))
        self.downButton.setText(_translate("MainWindow", "down"))
        self.label_14.setText(_translate("MainWindow", "joueur suivant:"))
        self.joueurSuivlabel.setText(_translate("MainWindow", " blanc"))
        self.affichage_label_21.setText(_translate("MainWindow", "cliquer le bouton \" humain vs humain \" pour afficher le plateau"))
        self.msg_Label.setText(_translate("MainWindow", "Bienvenu au jeu quoridor !"))
        self.label_7.setText(_translate("MainWindow", "Lambdda for TD"))
        self.comparepushButton.setText(_translate("MainWindow", "compare"))
        self.label.setText(_translate("MainWindow", "Nom de fichier à sauvegarder"))
        self.loadFileButton.setText(_translate("MainWindow", "Load file"))
        self.label_13.setText(_translate("MainWindow", "Nombre de neurones internes"))
        self.label_8.setText(_translate("MainWindow", "Nombre de tours pour entrainer l\'IA"))
        self.saveFileButton.setText(_translate("MainWindow", "Save file"))
        self.label_4.setText(_translate("MainWindow", "Nombre de murs"))
        self.newIAButton.setText(_translate("MainWindow", "Create New IA"))
        self.label_2.setText(_translate("MainWindow", "Nom de fichier à charger"))
        self.label_3.setText(_translate("MainWindow", "Taille du plateau "))
        self.label_11.setText(_translate("MainWindow", "Player1"))
        self.label_9.setText(_translate("MainWindow", "Nombre de tours pour comparer l\'IA"))
        self.player2_comboBox.setItemText(0, _translate("MainWindow", "Humain"))
        self.player2_comboBox.setItemText(1, _translate("MainWindow", "IA"))
        self.label_6.setText(_translate("MainWindow", "Learning rate"))
        self.label_12.setText(_translate("MainWindow", "Player 2"))
        self.ia_humainButton.setText(_translate("MainWindow", "IA vs Humain"))
        self.label_5.setText(_translate("MainWindow", "Epsillon"))
        self.strategy_comboBox.setItemText(0, _translate("MainWindow", "Q-learning"))
        self.strategy_comboBox.setItemText(1, _translate("MainWindow", "TD-lambda"))
        self.label_10.setText(_translate("MainWindow", "IA strategy"))
        self.direction_label.setText(_translate("MainWindow", "TextLabel"))
        self.humainButton.setText(_translate("MainWindow", "humain vs humain"))
        self.player1_comboBox.setItemText(0, _translate("MainWindow", "IA"))
        self.player1_comboBox.setItemText(1, _translate("MainWindow", "Humain"))
        self.trainIAButton.setText(_translate("MainWindow", "Train the IA"))

